-- 2026-09-27 uluslararası tur: TCMB'nin günlük kur verdiği para birimleri.
-- EKLEMELİ. ADD VALUE, bu değerleri KULLANAN DML'den AYRI migration'da
-- (docs/migration-safety.md § Enum).
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'AZN';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'SEK';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'NOK';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'DKK';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'BGN';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'RON';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'KRW';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'SAR';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'QAR';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'KWD';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'AUD';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'CAD';
